@startuml

!theme mars

Person as "Visiteur, Utilisateur, Auteur ou Admin" -> ArticleController : GET /articles

ArticleController -> Database : récupération des articles avec pagination
Database --> ArticleController : return

ArticleController -> Twig : render('article/articles', ['articles' => $articles])
Twig --> Person : affichage de l'ensemble des articles

@enduml