@startuml

!theme mars

Person as "Utilisateur" -> MyAccountController : GET /account/{id}/password/update

alt IsBadPerson
    MyAccountController -> Renderer : redirect('homepage')
    Renderer --> Person : affichage de la page d'accueil
else IsGoodPerson
    MyAccountController -> Validator : validation des données
    Validator --> MyAccountController : return
    alt IsNotValid
        MyAccountController -> Renderer : redirectt=ToLastPage(['error' => $error])
        Renderer --> Person : affichage du profil avec un message d'erreur
    else PasswordConfirmationMatch
        MyAccountController -> Database : vérifie que l'ancien mot de passe correspond
        Database --> MyAccountController : return

        alt LastPasswordNotMatch
            MyAccountController -> Renderer : redirectt=ToLastPage(['error' => $error])
            Renderer --> Person : affichage du profil avec un message d'erreur
        else LastPasswordMatch
            MyAccountController -> Database : modifier le mot de passe
            Database --> MyAccountController : return

            alt PasswordIsNotSaved
                MyAccountController -> Renderer : redirectt=ToLastPage(['error' => $error])
                Renderer --> Person : affichage du profil avec un message d'erreur
            else PasswordIsSaved
                MyAccountController -> Renderer : redirectt=ToLastPage(['success' => $success])
                Renderer --> Person : affichage du profil avec un message de succès
            end
        end
    end
end
@enduml