@startuml

!theme plain

Person as "Auteur ou Admin" -> ContactController : GET /dashboard/contact/{id}

alt IsNotAdmin
    ContactController -> Renderer : redirect('errors/401')
    Renderer --> Person : affichage de la page d'erreur
else IsAdmin
    ContactController -> Database : récupération de la demande
    Database --> ContactController : return

    alt ContactNotExist
        ContactController -> Renderer : render('/dashboard/contact/contacts', ['error' => $error]})
        Renderer --> Person : affichage de toutes les demandes de contact avec un message d'erreur
    else RequestExist
        ContactController -> Renderer : render('dashboard/contact/contact.php', ['contact' => $contact])
        Renderer --> Person : affichage de la demande de contact
    end
end

@enduml