@startuml

!theme plain

Person as "Auteur ou Admin" -> ContactController : GET /dashboard/contacts

alt IsNotAdmin
    ContactController -> Renderer : redirect('errors/401.php')
    Renderer --> Person : affichage de la page d'erreur
else IsAdmin
    ContactController -> Database : récupération des demandes de contact
    Database --> ContactController : return
    ContactController -> Renderer : render('dashboard/contact/contacts.php', ['contacts' => $contacts])
    Renderer --> Person : affichage de l'ensemble des demandes de contact
end

@enduml