@startuml

!theme mars

Person as "Utilisateur, Auteur ou Admin" -> CommentController : POST /article/{id}/comment/add

alt IsNotLogin
CommentController -> Renderer : redirect('/login')
else IsLogin
CommentController -> Validator : validation des données
    alt DataIsNotValid
    CommentController -> Renderer : render('/article/{id}', ['error' => $error])
    Renderer --> Person : affichage de l'article avec un message d'erreur
    else DataIsValid
    CommentController -> Database : ajout du commentaire
    Database --> CommentController : return
        alt CommentIsNotAdd
        CommentController -> Renderer : render('/article/{id}', ['error' => $error])
        Renderer --> Person : affichage de l'article avec un message d'erreur
        else CommentIsAdd
        CommentController -> Renderer : render('/article/{id}', ['success' => $success])
        Renderer --> Person : affichage de l'article avec un message de succès
        end
    end
end
@enduml