@startuml

!theme plain

Person as "Utilisateur, Auteur ou Admin" -> CommentController : DELETE /article/{id}/comment/{id}

alt IsNotLogin
CommentController -> Renderer : redirect('/login')
Renderer --> Person : Affichage de la page de connexion
else IsLogin
CommentController -> Database : récupération des infos du commentaire
Database --> CommentController : return
    alt IsBadPerson
    CommentController -> Renderer : render('/article/{id}', ['error' => $error])
    Renderer --> Person : affichage de l'article avec un message d'erreur
    else IsGoodPerson (admin ou auteur ou celui qui a écrit le commentaire)
    CommentController -> Database : suppression du commentaire
    Database --> CommentController : return
        alt CommentIsNotDeleted
        CommentController -> Renderer : render('/article/{id}', ['error' => $error])
        Renderer --> Person : affichage de l'article avec un message d'erreur
        else CommentIsDeleted
        CommentController -> Renderer : render('/article/{id}', ['success' => $success])
        Renderer --> Person : affichage de l'article avec un message de succès
        end
    end
end
@enduml