@startuml

!theme plain

Person as "Utilisateur, Auteur, ou Admin" -> CommentController : PUT /article/{id}/comment/{id}

alt IsNotLogin
CommentController -> Renderer : redirect('/login')
else IsLogin
CommentController -> Database : récupération des infos du commentaire
Database --> CommentController : return
    alt CommentNotExist or IsBadPerson
    CommentController -> Renderer : render('/article/{id}', ['error' => $error])
    Renderer --> Person : affichage de l'article avec un message d'erreur
    else CommentExist and IsGoodPerson
    CommentController -> Database : modification du commentaire
    Database --> CommentController : return
        alt CommentIsNotUpdated
        CommentController -> Renderer : render('/article/{id}', ['error' => $error])
        Renderer --> Person : affichage de l'article avec un message d'erreur
        else CommentIsUpdated
        CommentController -> Renderer : render('/article/{id}', ['success' => $success])
        Renderer --> Person : affichage de l'article avec un message de succès
        end
    end
end
@enduml