@startuml

!theme plain

Person as "Utilisateur, Auteur ou Admin" -> AccountController : GET /account/{id}/password/update

alt IsNotLogin
AccountController -> Renderer : rendirect('/login')
else IsLogin
    alt IsBadPerson
        AccountController -> Renderer : redirect('error/401')
        Renderer --> Person : affichage de la page d'erreur
    else IsGoodPerson
        AccountController -> Renderer : render('account/update-password', ['id' => $id])
        Renderer --> Person : affichage du formulaire de modification de mot de passe

        Person -> AccountController : PUT /account/{id}/password/update
        alt IsNotLogin
        AccountController -> Renderer : redirect('/login')
        else IsLogin
            alt IsBadPerson
                AccountController -> Renderer : redirect('error/401')
                Renderer --> Person : affichage de la page d'erreur
            else IsGoodPerson
                AccountController -> Validator : validation des données
                Validator --> AccountController : return
                alt PasswordConfirmationNotMatch
                    AccountController -> Renderer : render('account/update-password', ['id' => $id, 'error' => $error])
                    Renderer --> Person : affichage du formulaire avec un message d'erreur
                else PasswordConfirmationMatch
                    AccountController -> Database : vérifie que l'ancien mot de passe correspond
                    Database --> AccountController : return

                    alt LastPasswordNotMatch
                        AccountController -> Renderer : render('account/update-password', ['id' => $id, 'error' => $error])
                        Renderer --> Person : affichage du formulaire avec un message d'erreur
                    else LastPasswordMatch
                        AccountController -> Database : modifier le mot de passe
                        Database --> AccountController : return

                        alt PasswordIsNotSaved
                            AccountController -> Renderer : render('account/update-password', ['id' => $id, 'error' => $error])
                            Renderer --> Person : affichage du formulaire avec un message d'erreur
                        else PasswordIsSaved
                            AccountController -> Renderer : render('account/update-password', ['id' => $id, 'success' => $success])
                            Renderer --> Person : affichage du formulaire avec un message de succès
                        end
                    end
                end
            end
        end





    end
end
@enduml