@startuml

!theme plain

Visiteur -> LoginController : GET /login
alt IsLogin
LoginController -> Renderer : render('/account', 'account' => $account)
Renderer --> Visiteur : affichage de son profil

else IsNotLogin
LoginController -> Renderer : render('/login')
Renderer --> Visiteur : affichage du formulaire de connexion
end

Visiteur -> LoginController : POST /login
alt IsLogin
    LoginController -> Renderer : render('/account', 'account' => $account)
    Renderer --> Visiteur : affichage de son profil
else IsNotLogin
    LoginController -> Database : vérifier que l'adresse mail et le mot de passe correspondent
    Database --> LoginController : return

    alt AccountNotCorresponding
    LoginController -> Renderer : render('/login', ['error' => $error])
    Renderer --> Visiteur : affichage du formulaire de connexion avec une erreur
    else AccountCorresponding
    LoginController -> Session : enregistrement de l'utilisateur en session
    LoginController -> Renderer : render('/account')
    Renderer --> Visiteur : affichage de son compte
    end
end



@enduml