@startuml

!theme plain

Person as "Utilisateur connecté" -> LogoutController : GET /logout
alt IsNotLogin
LogoutController -> Renderer : redirect('/home')
Renderer --> Person : affichage de l'accueil
else IsLogin
LogoutController -> Session : suppression de l'utilisateur en session
LogoutController -> Renderer : redirect('/login')
Renderer --> Person : affichage du formulaire de connexion
end
@enduml