@startuml

!theme plain

Person as "Admin" -> AccountController : PUT /dashboard/user/{id}/set-author

alt IsNotAdmin
    ArticleController -> Renderer : redirect('errors/401.php')
    Renderer --> Person : Affichage de la page d'erreur
else IsAdmin
    ArticleController -> Database : modification de l'utilisateur
    Database --> ArticleController : return

    alt IsNotUpdated
        ArticleController -> Renderer : render('/dashboard/user/{id}', ['error' => $error])
        Renderer --> Person : affichage du compte avec une erreur
    else IsUpdated
        ArticleController -> Renderer : render('/dashboard/user/{id}', ['success' => $success])
        Renderer --> Person : affichage du compte avec un message de succès
    end
end

@enduml