@startuml

!theme plain

Person as "Visiteur, Utilisateur, Auteur ou Admin" -> ArticleController : GET /articles

ArticleController -> Database : récupération des articles avec pagination
Database --> ArticleController : return

ArticleController -> Renderer : render('article/articles', ['articles' => $articles])
Renderer --> Person : affichage de l'ensemble des articles

@enduml