@startuml

!theme plain

Person as "Visiteur, Utilisateur, Author ou Admin" -> ArticleController : GET /article/{id}

ArticleController -> Database : récupération de l'article avec l'id
Database --> ArticleController : return

alt ArticleNotExist
ArticleController -> Renderer : redirect('/errors/404.php')
Renderer --> Person : Affichage de l'ensemble des articles avec un message d'erreur

else ArticleExist
ArticleController -> Renderer : render('article/article', ['article' => $article])
Renderer --> Person : Affichage de l'article
end


@enduml