@startuml

!theme plain

Person as "Author ou Admin" -> ArticleController : DELETE /dashboard/article/{id}

alt IsNotAuthorize
ArticleController -> Renderer : redirect('/errors/401.php')
Renderer --> Person : affichage de la page d'erreur
else IsAuthorize
ArticleController -> Database : suppression de l'article
Database --> ArticleController : return

    alt IsNotDeleted
    ArticleController -> Renderer : render('/article/{id}', ['error' => $error])
    Renderer --> Person : affichage formulaire modification article avec message d'erreur
    else IsDeleted
    ArticleController -> Renderer : render('/dashboard/articles', ['success' => $success])
    Renderer --> Person : affichage de l'ensemble des articles
    end
end

@enduml